### ISSUE TITLE
validate function

### ISSUE THREAD

**Issue by jrmiller82** [hanelyp/fancydice#10]
Is there something going on with the SHA1 function? I can't get any of my hashes to = the secure. I'm trying to write a script that will go through the entire database and replace the bbcode with the resulting dice rolls.

**Comment by hanelyp** [comment]
In event/main_listener.php function validate()?  That's producing a code to sign the roll tag and detect editing of the tag.  Not necessary if the only intention is to compute the dice rolls.  config['fancyDiceSecure'] is a random seed created when the plugin is installed.  Other parameters come from the bbcode tag.
