### ISSUE TITLE
dice spec are not case-sensitive

### ISSUE THREAD

**Issue by Jym77** [hanelyp/fancydice#3]
Hello and thanks for the extension.
I've had a bit of a hard time with definition of custom dice because it appears that the spec are not case-sensitive (and actually upper-case spec are not possible).
That is, I am using a 'red' die. Following your smilies 'die' example, I define (in the ACP) the spec 'red' => [correct HTML code to expand to numbered image].
From that, I can use [dice]red[1_6][/dice] and it works like a charm.
But, if I try to define the spec 'R' => red[1_6], it does not work (treated as no number).
However, if I define 'r' => red[1_6], then I can use _both_ [dice]r[/dice] and [dice]R[/dice] with the expected result.

Even if, in the end, it is no more a problem for me, the case-insensitivity is pretty confusing (it took me some debugging time to figure it out). If this is a voluntary choice on your part, could you mention it in the readme file?

**Comment by hanelyp** [comment]
That is a deliberate design choice to be case insensitive on the end user side, to minimize chance of confusion there.  You're right that this should be better documented for the admin side.

**Comment by Jym77** [comment]
OK, it does make sense. thanks for the answer.
