### ISSUE TITLE
Docs need better explanation on specifying new dice

### ISSUE THREAD

**Issue by jrmiller82** [hanelyp/fancydice#6]
Hi there! Love the dice roller; but, I can't seem to wrap my head around defining new dice specifications. Maybe 1 or two examples? Maybe how to do fate dice? I can't even grok the "houserule" specification in the code nor how to use it.

**Comment by hanelyp** [comment]
Unfortunately the flexibility of this dice roller means setting up specs isn't always simple.
Looks like fate dice are just like fudge dice, equal chance of +, -, or blank.  The speck for that would be
    `@["+","-"," "]
or
`@[1,-1,0]
depending on how you want them totaled.  Other samples are in the testfancydice.php file.

**Comment by jrmiller82** [comment]
Thank you for your prompt reply!
