### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by wargamesqcf** [hanelyp/fancydice#7]
I uploaded the master to the ext of my forums and I can't enable it.

**Comment by hanelyp** [comment]
And that is not nearly enough information for me to act on.  What version of phpbb? php?  error message in the server logs?

**Comment by wargamesqcf** [comment]
No error logs, I made phpBB/ext/hanelyp on my linux box, put fancydice-master into that go to ACP and went to customize and under extenstions nothing about fancy dice is there.

PHPBB verison i do think is 3.1.10

**Comment by wargamesqcf** [comment]
Should I go to an earlier version of PHPBB?

**Comment by hanelyp** [comment]
3.1.10 is more recent than I've tested the plugin with.

Can you give me an `ls -l` for /ext/hanelyp/fancydice/ ?  phpbb has a bad habit (in my opinion) of pretending that plugins with any of several problems simply don't exist.  Among the checks that can cause that is do directory names and plugin metadata match exactly.

**Comment by wargamesqcf** [comment]
@ubuntu:/var/www/html/forums# ls -l ext/hanelyp/fancydice/
total 240
drwxr-xr-x 2    4096 Nov 11 22:56 acp
drwxr-xr-x 3   4096 Nov 11 22:56 adm
-rw-r--r-- 1   1102 Nov 11 22:56 announce.txt
-rw-r--r-- 1   1586 Nov 11 22:56 bbcode.php
-rw-r--r-- 1   1072 Nov 11 22:56 composer.json
drwxr-xr-x 2   4096 Nov 11 22:56 config
-rw-r--r-- 1  154246 Nov 11 22:56 dicerolled.png
-rw-r--r-- 1  14812 Nov 11 22:56 dicerolled_trim.png
drwxr-xr-x 2    4096 Nov 11 22:56 event
-rw-r--r-- 1     991 Nov 11 22:56 ext.php
-rw-r--r-- 1   10881 Nov 11 22:56 fancydice.php
drwxr-xr-x 4   4096 Nov 11 22:56 language
drwxr-xr-x 2    4096 Nov 11 22:56 migrations
-rw-r--r-- 1    2710 Nov 11 22:56 README.md
-rw-r--r-- 1     466 Nov 11 22:56 releases.json
drwxr-xr-x 2 root root   4096 Nov 11 22:56 screenshot
drwxr-xr-x 3   4096 Nov 11 22:56 styles
-rw-r--r-- 1   2294 Nov 11 22:56 testfancydice.php
@ubuntu:/var/www/html/forums#

**Comment by wargamesqcf** [comment]
So my forums crashed today by giving out error500 none stop so I had to reinstall it, and now fancydice appears.
